name: dockerhub

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Front End
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:web"
          push: true
          tags: hooopo/ossinsight-web:latest
      - 
        name: Build and Push ETL Server
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:etl"
          push: true
          tags: hooopo/ossinsight-etl:latest

      - 
        name: Build and Push API Server
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:packages/api-server"
          push: true
          tags: hooopo/ossinsight-api:latest