name: Surge PR Preview

on:
  pull_request_target:
    paths:
      - 'web/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merg
      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.14.2
      - name: Use Node.js 18
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install
        run: pnpm i --frozen-lockfile --strict-peer-dependencies --shamefully-hoist
      - name: Lint
        run: |
          npm run lint:ci
          npm run typecheck

  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.14.2
      - name: Use Node.js 18
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install
        run: pnpm i --frozen-lockfile --strict-peer-dependencies --shamefully-hoist
      - name: Prefetch
        run: npm run prefetch
      - name: Build 🏗️
        run: OSSINSIGHT_PREVIEW=true npm run build
      - name: Deploy to ossinsight.surge.sh 🚀
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          teardown: true
          build: echo 'Deployed to surge'
          dist: './web/build'