name: Surge PR Preview (Temp for \#917)

on:
  pull_request_target:
    paths:
      - 'web/**'

jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Use Node.js 18
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install
        run: npm ci
      - name: Prefetch
        run: npm run prefetch
      - name: Build 🏗️
        run: npm run build
      - name: Deploy to ossinsight.surge.sh 🚀
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          teardown: true
          build: echo 'Deployed to surge'
          dist: './web/build'

