on:
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0

      - uses: actions/setup-node@v2
        with:
          node-version: v16.14.0
          cache: 'pnpm'

      - name: install deps
        run: pnpm i --frozen-lockfile --strict-peer-dependencies

      - name: validate all params.json
        run: |
          pnpm run gen:schema-ts
          pnpm run validate:params

      - name: build
        run: pnpm run build
