name: Verify Query Definition File

on:
  pull_request:
    paths:
      - 'api/**'

defaults:
  run:
    shell: bash
    working-directory: api

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v16.14.0
          cache: 'pnpm'
          cache-dependency-path: 'api/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --strict-peer-dependencies

      - name: Build
        run: pnpm run build

      - name: Verify Query Definition JSON
        run: |
          pnpm run gen:schema-ts
          pnpm run validate:params

      - name: Build Project
        run: pnpm run build
